### ISSUE TITLE
php artisan nova:breadcrumbs command stuck ...

### ISSUE THREAD

**Issue by scramatte** [bocanhcam/nova-breadcrumb#1]
Hi,

I've just installed your package on  Nova 4.35.5 
"php artisan nova:breadcrumbs"   stuck  and doesn't display nothing.

Any idea of what occurs here?

Regards

**Comment by bocanhcam** [comment]
Sorry for the late response. Have you run that command successfully? That command might take a few minutes to complete.
I will check it again

**Comment by bocanhcam** [comment]
I have checked, and no errors appear on my side. Please note that this command may take a few minutes to complete.

In version 1.0.7, I have added command output to make it clearer what is running and to display any potential errors.

Thank you for reporting this issue.
Feel free to let me know if you need any further assistance
